name: Build image for CloudRun

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  CLOUD_RUN_REGION: asia-northeast1
  # project-name but it can be anything you want
  REPO_NAME: bestdoctorecare-shop

jobs:
  build:
    name: Setup, Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    # This step is where our service account will be authenticated
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
        service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
        service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

    - name: Enable the necessary APIs and enable docker auth
      run: |-
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable run.googleapis.com
        gcloud --quiet auth configure-docker
    - name: Build and tag image
      run: |-
        docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:${{ env.RELEASE_VERSION }}"
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:${{ env.RELEASE_VERSION }}
